pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deliver') {
            agent {
                docker {
                    image 'cdrx/pyinstaller-linux:python2'
                }
            }
            steps {
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }
    }
}

// node {
//     stage('Build') {
//         def pythonImage = docker.build("python:2-alpine")

//         pythonImage.inside {
//             sh 'python -m py_compile sources/add2vals.py sources/calc.py'
//         }
//     }
//     stage('Test') {
//         def pytestImage = docker.build("qnib/pytest")

//         pytestImage.inside {
//             sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
//             junit 'test-reports/results.xml'
//         }
//     }
//     stage('Deliver') {
//         def pyinstallerImage = docker.build("cdrx/pyinstaller-linux:python2")

//         pytestImage.inside {
//             sh 'pyinstaller --onefile sources/add2vals.py'
//             archiveArtifacts 'dist/add2vals'
//         }
//     }
// }
